/** SoFIFA nation label → flagcdn.com code (supports gb-eng, etc.). */
const NATION_FLAG: Record<string, string> = {
  England: "gb-eng",
  Scotland: "gb-sct",
  Wales: "gb-wls",
  "Northern Ireland": "gb-nir",
  Germany: "de",
  Spain: "es",
  Argentina: "ar",
  France: "fr",
  Uruguay: "uy",
  Italy: "it",
  Netherlands: "nl",
  Brazil: "br",
  Türkiye: "tr",
  Turkey: "tr",
  Poland: "pl",
  Venezuela: "ve",
  "China PR": "cn",
  Ecuador: "ec",
  Peru: "pe",
  Paraguay: "py",
  "United States": "us",
  Colombia: "co",
  Sweden: "se",
  "Korea Republic": "kr",
  Norway: "no",
  Romania: "ro",
  "Republic of Ireland": "ie",
  Portugal: "pt",
  "Saudi Arabia": "sa",
  Japan: "jp",
  India: "in",
  Belgium: "be",
  Bolivia: "bo",
  Australia: "au",
  Austria: "at",
  Denmark: "dk",
  Mexico: "mx",
  Switzerland: "ch",
  Chile: "cl",
  Croatia: "hr",
  Morocco: "ma",
  Senegal: "sn",
  Nigeria: "ng",
  Ghana: "gh",
  "Côte d'Ivoire": "ci",
  "Cote d'Ivoire": "ci",
  Serbia: "rs",
  Greece: "gr",
  Czechia: "cz",
  "Czech Republic": "cz",
  "South Africa": "za",
  Ukraine: "ua",
  Algeria: "dz",
  Canada: "ca",
  "Bosnia and Herzegovina": "ba",
  Cameroon: "cm",
  Finland: "fi",
  Hungary: "hu",
  Kosovo: "xk",
  Mali: "ml",
  Russia: "ru",
  Albania: "al",
  Slovakia: "sk",
  Slovenia: "si",
  "New Zealand": "nz",
  Israel: "il",
  Guinea: "gn",
  Iceland: "is",
  Gambia: "gm",
  Bulgaria: "bg",
  Qatar: "qa",
  "Guinea-Bissau": "gw",
  Angola: "ao",
  Jamaica: "jm",
  Cyprus: "cy",
  Georgia: "ge",
  "North Macedonia": "mk",
  "Burkina Faso": "bf",
  Tunisia: "tn",
  "Cape Verde": "cv",
  "Cabo Verde": "cv",
  "DR Congo": "cd",
  "Congo DR": "cd",
  Panama: "pa",
  Haiti: "ht",
  Egypt: "eg",
  Iran: "ir",
  Iraq: "iq",
  "Costa Rica": "cr",
  Honduras: "hn",
  Guatemala: "gt",
  "El Salvador": "sv",
  Nicaragua: "ni",
  Cuba: "cu",
  "Dominican Republic": "do",
  "Trinidad and Tobago": "tt",
  Zambia: "zm",
  Zimbabwe: "zw",
  Kenya: "ke",
  Uganda: "ug",
  Tanzania: "tz",
  Ethiopia: "et",
  Libya: "ly",
  Sudan: "sd",
  "Democratic Republic of Congo": "cd",
  Congo: "cg",
  Gabon: "ga",
  Benin: "bj",
  Togo: "tg",
  Niger: "ne",
  Mauritania: "mr",
  Mozambique: "mz",
  Namibia: "na",
  Botswana: "bw",
  Armenia: "am",
  Azerbaijan: "az",
  Belarus: "by",
  Estonia: "ee",
  Latvia: "lv",
  Lithuania: "lt",
  Luxembourg: "lu",
  Malta: "mt",
  Moldova: "md",
  Montenegro: "me",
  "Faroe Islands": "fo",
  Kazakhstan: "kz",
  Uzbekistan: "uz",
  Thailand: "th",
  Vietnam: "vn",
  Indonesia: "id",
  Malaysia: "my",
  Singapore: "sg",
  Philippines: "ph",
  "Hong Kong": "hk",
  "United Arab Emirates": "ae",
  Oman: "om",
  Bahrain: "bh",
  Kuwait: "kw",
  Jordan: "jo",
  Lebanon: "lb",
  Syria: "sy",
  Palestine: "ps",
  Yemen: "ye",
  Afghanistan: "af",
  Pakistan: "pk",
  Bangladesh: "bd",
  "Sri Lanka": "lk",
  Nepal: "np",
  Myanmar: "mm",
  Cambodia: "kh",
  Laos: "la",
  Mongolia: "mn",
  "New Caledonia": "nc",
  Fiji: "fj",
  Tahiti: "pf",
  "Papua New Guinea": "pg",
  "Solomon Islands": "sb",
  "Equatorial Guinea": "gq",
  "Central African Republic": "cf",
  Rwanda: "rw",
  Burundi: "bi",
  Malawi: "mw",
  Madagascar: "mg",
  Comoros: "km",
  Eswatini: "sz",
  Lesotho: "ls",
  Suriname: "sr",
  Guyana: "gy",
  Curacao: "cw",
  "Curaçao": "cw",
  "Curaçao": "cw",
  Aruba: "aw",
  "Puerto Rico": "pr",
  "Korea DPR": "kp",
  "Chinese Taipei": "tw",
};

export function nationFlagSrc(nation: string, size = 40): string | null {
  const code = NATION_FLAG[nation.trim()];
  if (!code) return null;
  return `https://flagcdn.com/w${size}/${code}.png`;
}
